version: '3.7'

services: 
  web:
    image: web
    build:
      context: .
      dockerfile: web.dockerfile
    command: python3 Dunno/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    
