# Generated by Django 3.1.3 on 2020-11-12 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=1000)),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2020, 11, 12, 15, 7, 47, 814865, tzinfo=utc
                        )
                    ),
                ),
            ],
        ),
    ]
