# Generated by Django 3.1.3 on 2020-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20201112_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=400),
        ),
    ]
